name: Build the plugin and release on GitHub
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cargo-build:
    strategy:
      matrix:
        target:
        - x86_64-pc-windows-msvc
        - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      # Build plugin
      - run: cargo build --release --target ${{ matrix.target }}

      # Copy build output binary depending on target
      - run: cp "./target/x86_64-unknown-linux-gnu/release/libts3joininfo.so" "output/ts3joininfo_linux_amd64.so"
        if: ${{ matrix.target == x86_64-unknown-linux-gnu }}

      - run: cp "./target/x86_64-unknown-linux-gnu/release/libts3joininfo.so" "output/ts3joininfo_linux_x86.so"
        if: ${{ matrix.target == x86_64-unknown-linux-gnu }}

      - run: cp "./target/x86_64-unknown-linux-gnu/release/ts3joininfo.dll" "output/ts3joininfo_win64.dll"
        if: ${{ matrix.target == x86_64-pc-windows-msvc }}

      - run: cp "./target/x86_64-unknown-linux-gnu/release/ts3joininfo.dll" "output/ts3joininfo_win32.dll"
        if: ${{ matrix.target == x86_64-pc-windows-msvc }}

      # Allow other jobs to access output binaries
      - name: Store build output binary
        uses: actions/upload-artifact@v3
        with:
          name: plugin-binary
          path: |
            "output/*.so"
            "output/*.dll"